#!/usr/bin/env bash

arg_methods[${#arg_methods[@]}]="start"

function pluginHelp_start(){
    cat << EOF
start
EOF
}

function plugin_start(){

    if [[ -f $PATH_ROOT/var/mysqld.pid ]]; then
        log ERROR "mysql(`cat $PATH_ROOT/var/mysqld.pid`) is running"
        return 1
    fi

    nohup $arg_baseDir/bin/mysqld_safe \
        --defaults-file=$PATH_ROOT/etc/mysql.config >$PATH_ROOT/log/nohup.log 2>$PATH_ROOT/log/nohup.err &

    sleep 5

    if [[ ! -f $PATH_ROOT/var/mysqld.pid ]]; then
        log ERROR "mysql start fail"
        return 1
    fi

    log INFO "mysql start success"

    return 0

}
